/**
 * Generates the illustration library from `illustrations/<profile>/<name>/`.
 *
 * Each profile folder has one folder per illustration containing exactly one
 * image – an `.svg`, or a raster `.png`/`.webp`/`.jpg` – and a `meta.json`
 * (see `meta.schema.json`), and optionally a
 * `colors.json` (the palette used by its illustrations, with light and dark
 * values). Without `colors.json` the illustrations keep their drawn colours:
 * no dark mode and no colour slots.
 *
 * For every profile this writes, under `generated/illustrations/<profile>/`:
 *   - `react/<Name>.tsx` + `react/index.ts`  React components
 *   - `svg.ts`                                framework-agnostic SVG strings
 *   - `meta.ts`                               titles, tags, colours, slots
 * and, under `dist/illustrations/`, a `<profile>.css` with the colour
 * variables plus an `index.css` combining every profile. Raster images are
 * copied as-is to `dist/illustrations/<profile>/`, and `images.ts` exports
 * each one's URL through an asset import (`import url from './file.png'`), so
 * bundlers emit the file and return its URL – also when server rendering –
 * instead of inlining base64 in the JS. The shared types and
 * helpers in `src/illustrations/index.ts` are copied to
 * `generated/illustrations/index.ts` with the profile list and loaders added.
 *
 * Colours: hard-coded palette colours are replaced with
 * `var(--varde-illustration-<profile>-<colour>, <light hex>)`, so the SVGs
 * render correctly without the CSS and switch to the dark palette when the
 * CSS is loaded and `data-color-scheme="dark"` is set.
 *
 * Colour slots: a layer named `Former [red,yellow]` in Illustrator marks
 * the shape(s) as recolourable to the listed palette colours. The build reads
 * the marker from the exported `data-name` attribute (Illustrator flattens the
 * brackets in `id`), gives the slot its own variable that falls back to the
 * drawn colour, adds a typed prop to the React component and lists the slot
 * in `meta.ts`. Layers without a `[...]` list are never recoloured.
 *
 * Run with `node scripts/build-illustrations.ts` (Node ≥ 22.18 strips types),
 * then compile `generated/` with `tsc -p tsconfig.build.json`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';
import { type CustomPlugin, optimize, type XastElement } from 'svgo';
import type {
  IllustrationColor,
  IllustrationSlot,
  RasterIllustrationMeta,
  VectorIllustrationMeta,
} from '../src/illustrations/index.ts';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const sourceDir = path.join(packageRoot, 'illustrations');
const runtimeSource = path.join(
  packageRoot,
  'src',
  'illustrations',
  'index.ts',
);
const generatedDir = path.join(packageRoot, 'generated', 'illustrations');
const distDir = path.join(packageRoot, 'dist', 'illustrations');

const VARIABLE_PREFIX = '--varde-illustration';
const GENERATED_HEADER =
  '// Generated by scripts/build-illustrations.ts – do not edit.';

type ColorDefinition = { label?: string; light: string; dark: string };
type Palette = Record<string, ColorDefinition>;

type Meta = {
  $schema?: string;
  title: string;
  description?: string;
  tags: string[];
};

type VectorIllustration = VectorIllustrationMeta & { svg: string };
type RasterIllustration = RasterIllustrationMeta & { source: string };

const SLUG_PATTERN = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
const ILLUSTRATION_FILE = /\.(svg|png|webp|jpe?g)$/i;
const HEX_COLOR = /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i;
const ANY_HEX_COLOR = /#(?:[0-9a-f]{3}|[0-9a-f]{6})\b/gi;
const COLOR_ATTRIBUTES = [
  'fill',
  'stroke',
  'stop-color',
  'flood-color',
  'lighting-color',
];
/** Keep full, lower-case-insensitive hex values so palette lookups are exact. */
const CONVERT_COLORS = {
  currentColor: false,
  names2hex: true,
  rgb2hex: true,
  shorthex: false,
  shortname: false,
};
/** Props already used by the generated component, so slots can't take them. */
const RESERVED_PROPS = new Set([
  'title',
  'titleId',
  'style',
  'ref',
  'key',
  'children',
]);

const toPascalCase = (slug: string) =>
  slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const toCamelCase = (slug: string) => {
  const pascal = toPascalCase(slug);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

/** "Former og figurer" → "former-og-figurer" (æøå folded to ASCII). */
const slugify = (text: string) =>
  text
    .toLowerCase()
    .replace(/æ/g, 'ae')
    .replace(/ø/g, 'o')
    .replace(/å/g, 'a')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const readJson = <T>(file: string): T =>
  JSON.parse(fs.readFileSync(file, 'utf8')) as T;

const listDirectories = (dir: string) =>
  fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

/** Expand `#abc` to `#aabbcc` and lower-case, so palette lookups are stable. */
const normalizeHex = (hex: string) => {
  const value = hex.toLowerCase();
  if (value.length === 4) {
    return `#${value[1]}${value[1]}${value[2]}${value[2]}${value[3]}${value[3]}`;
  }
  return value;
};

/** The profile's palette, or null when it has no `colors.json`. */
const readPalette = (profile: string): IllustrationColor[] | null => {
  const file = path.join(sourceDir, profile, 'colors.json');
  if (!fs.existsSync(file)) return null;

  const palette = readJson<Palette>(file);

  return Object.entries(palette).map(([name, definition]) => {
    if (!SLUG_PATTERN.test(name)) {
      throw new Error(
        `Colour "${name}" in ${profile}/colors.json must be kebab-case (a-z, 0-9, -).`,
      );
    }
    for (const mode of ['light', 'dark'] as const) {
      if (!/^#[0-9a-f]{6}$/i.test(definition?.[mode] ?? '')) {
        throw new Error(
          `Colour "${name}" in ${profile}/colors.json needs a 6-digit hex "${mode}" value.`,
        );
      }
    }
    return {
      name,
      label: definition.label ?? name,
      variable: `${VARIABLE_PREFIX}-${profile}-${name}`,
      light: normalizeHex(definition.light),
      dark: normalizeHex(definition.dark),
    };
  });
};

const readMeta = (dir: string): Meta => {
  const file = path.join(dir, 'meta.json');
  if (!fs.existsSync(file)) {
    throw new Error(`Missing ${path.relative(packageRoot, file)}`);
  }

  const meta = readJson<Meta>(file);
  const relative = path.relative(packageRoot, file);

  if (typeof meta.title !== 'string' || meta.title.trim() === '') {
    throw new Error(`${relative}: "title" must be a non-empty string.`);
  }
  if (
    !Array.isArray(meta.tags) ||
    meta.tags.some((tag) => typeof tag !== 'string' || tag.trim() === '')
  ) {
    throw new Error(`${relative}: "tags" must be an array of strings.`);
  }
  if (meta.description !== undefined && typeof meta.description !== 'string') {
    throw new Error(`${relative}: "description" must be a string.`);
  }

  return meta;
};

/** The folder's one image file: an `.svg` or a raster `.png`/`.webp`/`.jpg`. */
const findIllustrationFile = (dir: string) => {
  const files = fs
    .readdirSync(dir)
    .filter((file) => ILLUSTRATION_FILE.test(file));
  const relative = path.relative(packageRoot, dir);

  if (files.length === 0) {
    throw new Error(`${relative}: no .svg, .png, .webp or .jpg file found.`);
  }
  if (files.length > 1) {
    throw new Error(
      `${relative}: expected exactly one image file, found ${files.join(', ')}.`,
    );
  }
  return path.join(dir, files[0]);
};

const rasterFormat = (file: string): RasterIllustrationMeta['format'] => {
  const extension = path.extname(file).slice(1).toLowerCase();
  return extension === 'jpeg' ? 'jpg' : (extension as 'png' | 'webp' | 'jpg');
};

/** Width and height from a PNG's IHDR chunk; 0×0 for other formats. */
const rasterSize = (file: string) => {
  const header = fs.readFileSync(file).subarray(0, 24);
  const isPng = header.readUInt32BE(0) === 0x89504e47;
  return isPng
    ? { width: header.readUInt32BE(16), height: header.readUInt32BE(20) }
    : { width: 0, height: 0 };
};

// ---------------------------------------------------------------------------
// Colours and slots
// ---------------------------------------------------------------------------

const SLOT_MARKER = /^(.*?)\s*\[([^\]]*)\]\s*$/;

/** Parse `Former [red,yellow]` → { label: 'Former', colors: [...] }. */
const parseSlotMarker = (
  layerName: string,
  colors: IllustrationColor[],
  context: string,
) => {
  const match = layerName.match(SLOT_MARKER);
  if (!match) return null;

  const label = match[1].trim();
  const list = match[2]
    .split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);

  if (!label) {
    throw new Error(
      `${context}: layer "${layerName}" has no name before [...].`,
    );
  }
  if (list.length === 0) {
    throw new Error(
      `${context}: layer "${layerName}" has an empty colour list. Remove the brackets to keep the colour fixed.`,
    );
  }
  const known = new Set(colors.map((color) => color.name));
  for (const color of list) {
    if (!known.has(color)) {
      throw new Error(
        `${context}: layer "${layerName}" lists unknown colour "${color}". Use one of: ${[...known].join(', ')}.`,
      );
    }
  }
  return { label, colors: [...new Set(list)] };
};

/**
 * Register the slot for a layer marked `Name [colour,…]`, or return undefined
 * for ordinary layers. Layers sharing a name share one slot.
 */
const registerSlot = (
  layerName: string,
  slots: Map<string, IllustrationSlot>,
  colors: IllustrationColor[],
  profile: string,
  name: string,
) => {
  const context = `${profile}/${name}`;
  const marker = parseSlotMarker(layerName, colors, context);
  if (!marker) return undefined;

  const slotName = slugify(marker.label);
  if (!SLUG_PATTERN.test(slotName)) {
    throw new Error(
      `${context}: layer "${layerName}" needs a name starting with a letter.`,
    );
  }
  const prop = toCamelCase(slotName);
  if (RESERVED_PROPS.has(prop)) {
    throw new Error(
      `${context}: layer name "${marker.label}" clashes with the "${prop}" prop – pick another name.`,
    );
  }

  const existing = slots.get(slotName);
  if (existing) {
    if (existing.colors.join() !== marker.colors.join()) {
      throw new Error(
        `${context}: layers named "${marker.label}" list different colours. Layers with the same name share one slot and must agree.`,
      );
    }
    return existing;
  }

  const slot: IllustrationSlot = {
    name: slotName,
    label: marker.label,
    prop,
    variable: `${VARIABLE_PREFIX}-${profile}-${name}-${slotName}`,
    default: '',
    colors: marker.colors,
  };
  slots.set(slotName, slot);
  return slot;
};

/**
 * svgo plugin that swaps palette colours for CSS variables and registers
 * colour slots from `data-name` markers. Inside a slotted element, shapes
 * drawn in the slot's colour get the slot variable (falling back to the
 * palette variable); everything else gets the palette variable.
 */
const themeColorsPlugin = (
  byHex: Map<string, IllustrationColor>,
  colors: IllustrationColor[],
  slots: Map<string, IllustrationSlot>,
  profile: string,
  name: string,
): CustomPlugin => ({
  name: 'vardeThemeColors',
  fn: () => {
    const stack: { node: XastElement; slot: IllustrationSlot }[] = [];

    return {
      element: {
        enter: (node: XastElement) => {
          const layerName = node.attributes['data-name'];
          const slot =
            layerName && registerSlot(layerName, slots, colors, profile, name);
          if (slot) stack.push({ node, slot });
          const active = stack.at(-1)?.slot;

          for (const attribute of COLOR_ATTRIBUTES) {
            const value = node.attributes[attribute];
            if (!value || !HEX_COLOR.test(value)) continue;
            const color = byHex.get(normalizeHex(value));
            if (!color) continue; // reported after optimisation
            const paletteVar = `var(${color.variable}, ${color.light})`;

            // The first palette colour met inside a slot (the marked element
            // itself comes first) is the colour that slot swaps.
            if (active && !active.default) active.default = color.name;

            node.attributes[attribute] =
              active && active.default === color.name
                ? `var(${active.variable}, ${paletteVar})`
                : paletteVar;
          }
        },
        exit: (node: XastElement) => {
          if (stack.at(-1)?.node === node) stack.pop();
        },
      },
    };
  },
});

/**
 * Optimise the SVG and swap palette colours for CSS variables. Any colour that
 * is not in the palette is left as-is and reported, so it can be added to
 * `colors.json` (or fixed in the SVG).
 */
const processSvg = (
  svg: string,
  profile: string,
  name: string,
  colors: IllustrationColor[],
  fixedColors: boolean,
) => {
  const context = `${profile}/${name}`;
  const byHex = new Map(colors.map((color) => [color.light, color]));
  const slots = new Map<string, IllustrationSlot>();

  // Pass 1: get every colour onto an attribute and swap it for a variable,
  // before preset-default merges paths, hoists attributes or drops data-name.
  const themed = optimize(svg, {
    multipass: false,
    plugins: [
      'mergeStyles',
      { name: 'inlineStyles', params: { onlyMatchedOnce: false } },
      'convertStyleToAttrs',
      { name: 'convertColors', params: CONVERT_COLORS },
      themeColorsPlugin(byHex, colors, slots, profile, name),
    ],
  }).data;

  // Pass 2: the usual optimisation.
  const optimized = optimize(themed, {
    multipass: true,
    plugins: [
      {
        name: 'preset-default',
        params: { overrides: { convertColors: CONVERT_COLORS } },
      },
      // Several illustrations may be inlined on one page – keep ids unique.
      { name: 'prefixIds', params: { prefix: name } },
      // Drop the root width/height so the container decides the size, and
      // Illustrator's data-name attributes (the viewBox is kept – svgo 4 no
      // longer removes it by default).
      {
        name: 'removeAttrs',
        params: { attrs: ['svg:(width|height)', 'data-name'] },
      },
    ],
  }).data;

  // Anything still hard-coded was not in the palette (or sat in a style).
  const unknown = new Set(
    (optimized.match(ANY_HEX_COLOR) ?? []).filter(
      (hex) => !byHex.has(normalizeHex(hex)),
    ),
  );
  if (unknown.size > 0 && !fixedColors) {
    console.warn(
      `  ⚠ ${context}: colour(s) ${[...unknown].join(', ')} are not in ${profile}/colors.json and will not follow the colour scheme.`,
    );
  }

  for (const slot of slots.values()) {
    if (!slot.default) {
      throw new Error(
        `${context}: layer "${slot.label}" is marked as a colour slot but no palette colour was found in it.`,
      );
    }
    if (!slot.colors.includes(slot.default)) {
      console.warn(
        `  ⚠ ${context}: layer "${slot.label}" is drawn in "${slot.default}" but does not list it – adding it.`,
      );
      slot.colors.unshift(slot.default);
    }
  }

  return { svg: optimized, slots: [...slots.values()] };
};

// ---------------------------------------------------------------------------
// React components
// ---------------------------------------------------------------------------

/**
 * SVGR renders only an inner `Svg` function (props + ref, no export); the
 * exported component is written by us below, so slot props never depend on
 * SVGR's output formatting.
 */
const buildReactComponent = async (
  svg: string,
  componentName: string,
  profile: string,
  slots: IllustrationSlot[],
) => {
  const inner = await transform(
    svg,
    {
      plugins: ['@svgr/plugin-jsx'],
      typescript: true,
      jsxRuntime: 'automatic',
      ref: true,
      titleProp: true,
      dimensions: false,
      expandProps: 'end',
      template: (variables, { tpl }) => tpl`
        ${variables.imports};
        ${variables.interfaces};
        const ${variables.componentName} = (${variables.props}) => (
          ${variables.jsx}
        );
      `,
    },
    { componentName: 'Svg' },
  );

  if (slots.length === 0) {
    return [
      GENERATED_HEADER,
      inner,
      `const ${componentName} = forwardRef(Svg);`,
      `export default ${componentName};`,
      '',
    ].join('\n');
  }

  const slotProps = slots
    .map(
      (slot) =>
        `  /** Colour of "${slot.label}". Defaults to "${slot.default}". */\n  ${slot.prop}?: ${slot.colors.map((color) => `'${color}'`).join(' | ')};`,
    )
    .join('\n');
  const slotVariables = slots
    .map((slot) => `'${slot.variable}': ${slot.prop}`)
    .join(', ');
  const destructured = slots.map((slot) => slot.prop).join(', ');

  return [
    GENERATED_HEADER,
    "import { applySlots } from '../../index.js';",
    inner,
    'interface SlotProps {',
    slotProps,
    '}',
    `const ${componentName} = forwardRef<SVGSVGElement, Parameters<typeof Svg>[0] & SlotProps>(`,
    `  ({ ${destructured}, style, ...props }, ref) =>`,
    `    Svg({ ...props, style: applySlots(style, '${VARIABLE_PREFIX}-${profile}', { ${slotVariables} }) }, ref),`,
    ');',
    `export default ${componentName};`,
    '',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

const buildProfile = async (profile: string) => {
  const profileDir = path.join(sourceDir, profile);
  const outDir = path.join(generatedDir, profile);
  const reactDir = path.join(outDir, 'react');
  fs.mkdirSync(reactDir, { recursive: true });

  const palette = readPalette(profile);
  const darkMode = palette !== null;
  const colors = palette ?? [];
  const illustrations: VectorIllustration[] = [];
  const rasters: RasterIllustration[] = [];

  for (const name of listDirectories(profileDir)) {
    if (!SLUG_PATTERN.test(name)) {
      throw new Error(
        `Illustration folder "${profile}/${name}" must be kebab-case (a-z, 0-9, -) and start with a letter.`,
      );
    }

    const dir = path.join(profileDir, name);
    const meta = readMeta(dir);
    const file = findIllustrationFile(dir);
    const exportName = toCamelCase(name);

    if (!file.endsWith('.svg')) {
      const format = rasterFormat(file);
      rasters.push({
        format,
        name,
        exportName,
        title: meta.title,
        description: meta.description,
        tags: meta.tags,
        file: `${name}.${format}`,
        ...rasterSize(file),
        source: file,
      });
      continue;
    }

    const rawSvg = fs.readFileSync(file, 'utf8');
    const { svg, slots } = processSvg(rawSvg, profile, name, colors, !darkMode);
    const componentName = toPascalCase(name);

    fs.writeFileSync(
      path.join(reactDir, `${componentName}.tsx`),
      await buildReactComponent(svg, componentName, profile, slots),
    );

    illustrations.push({
      format: 'svg',
      name,
      componentName,
      exportName,
      title: meta.title,
      description: meta.description,
      tags: meta.tags,
      viewBox: svg.match(/viewBox=["']([^"']+)["']/)?.[1],
      slots,
      svg,
    });
  }

  // Raster files sit next to the compiled `images.js` that points at them.
  fs.mkdirSync(path.join(distDir, profile), { recursive: true });
  for (const item of rasters) {
    fs.copyFileSync(item.source, path.join(distDir, profile, item.file));
  }
  fs.writeFileSync(
    path.join(outDir, 'images.ts'),
    [
      GENERATED_HEADER,
      '// URLs of the raster illustrations. Bundlers (Vite, webpack, Parcel)',
      '// emit each imported file as an asset and give back its URL.',
      '',
      ...rasters.map(
        (item) => `import ${item.exportName}Url from './${item.file}';`,
      ),
      '',
      ...rasters.map(
        (item) =>
          `export const ${item.exportName}: string = ${item.exportName}Url;`,
      ),
      ...(rasters.length === 0 ? ['export {};'] : []),
      '',
    ].join('\n'),
  );

  if (illustrations.length === 0 && rasters.length === 0) {
    console.warn(`  ⚠ ${profile}: no illustrations found.`);
  }

  fs.writeFileSync(
    path.join(reactDir, 'index.ts'),
    [
      GENERATED_HEADER,
      ...illustrations.map(
        (item) =>
          `export { default as ${item.componentName} } from './${item.componentName}.js';`,
      ),
      ...(illustrations.length === 0 ? ['export {};'] : []),
      '',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(outDir, 'svg.ts'),
    [
      GENERATED_HEADER,
      '// Framework-agnostic SVG strings. Load `@digdir/varde/illustrations.css`',
      '// (or `@digdir/varde/illustrations/<profile>.css`) for dark mode support.',
      '',
      ...illustrations.map(
        (item) =>
          `export const ${item.exportName} = ${JSON.stringify(item.svg)};`,
      ),
      // Keep the file a module when the profile has no SVG illustrations.
      ...(illustrations.length === 0 ? ['export {};'] : []),
      '',
    ].join('\n'),
  );

  const metaEntries = [
    ...illustrations.map(({ svg: _svg, ...rest }) => rest),
    ...rasters.map(({ source: _source, ...rest }) => rest),
  ].sort((a, b) => a.name.localeCompare(b.name));
  fs.writeFileSync(
    path.join(outDir, 'meta.ts'),
    [
      GENERATED_HEADER,
      "import type { IllustrationColor, IllustrationMeta } from '../index.js';",
      '',
      `export const profile = ${JSON.stringify(profile)};`,
      '',
      `export const darkMode = ${darkMode};`,
      '',
      `export const colors: IllustrationColor[] = ${JSON.stringify(colors, null, 2)};`,
      '',
      `export const illustrations: IllustrationMeta[] = ${JSON.stringify(metaEntries, null, 2)};`,
      '',
    ].join('\n'),
  );

  const declarations = (mode: 'light' | 'dark') =>
    colors.map((color) => `  ${color.variable}: ${color[mode]};`).join('\n');
  const css = !darkMode
    ? [
        `/* Generated by scripts/build-illustrations.ts – do not edit. */`,
        `/* The "${profile}" illustrations use fixed colours – nothing to load. */`,
        '',
      ].join('\n')
    : [
        `/* Generated by scripts/build-illustrations.ts – do not edit. */`,
        `/* Colours for the "${profile}" illustrations in @digdir/varde. */`,
        ':root,',
        `[data-color-scheme='light'] {`,
        declarations('light'),
        '}',
        '',
        `[data-color-scheme='dark'] {`,
        declarations('dark'),
        '}',
        '',
        '@media (prefers-color-scheme: dark) {',
        `  [data-color-scheme='auto'] {`,
        declarations('dark').replace(/^/gm, '  '),
        '  }',
        '}',
        '',
        '@media (prefers-color-scheme: light) {',
        `  [data-color-scheme='auto'] {`,
        declarations('light').replace(/^/gm, '  '),
        '  }',
        '}',
        '',
      ].join('\n');
  fs.writeFileSync(path.join(distDir, `${profile}.css`), css);

  const slotCount = illustrations.reduce(
    (sum, item) => sum + item.slots.length,
    0,
  );
  console.log(
    `  ✓ ${profile}: ${illustrations.length} SVG(s), ${slotCount} colour slot(s), ${rasters.length} image(s)`,
  );
  return css;
};

/** `@digdir/varde/illustrations`: the checked-in runtime plus generated data. */
const writeIndex = (profiles: string[]) => {
  const runtime = fs
    .readFileSync(runtimeSource, 'utf8')
    .replace(
      /^\/\*\*[\s\S]*?\*\/\n/,
      `${GENERATED_HEADER}\n// Source: src/illustrations/index.ts\n`,
    );

  const loaders = profiles.map(
    (profile) =>
      `  ${JSON.stringify(profile)}: () =>\n    loadIllustrationLibrary(import('./${profile}/meta.js'), import('./${profile}/svg.js'), import('./${profile}/images.js')),`,
  );

  // Lets tsc compile the asset imports in each profile's `images.ts`.
  fs.writeFileSync(
    path.join(generatedDir, 'assets.d.ts'),
    [
      GENERATED_HEADER,
      ...['png', 'webp', 'jpg'].map(
        (extension) =>
          `declare module '*.${extension}' {\n  const url: string;\n  export default url;\n}`,
      ),
      '',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(generatedDir, 'index.ts'),
    [
      runtime,
      '/** Profiles that ship illustrations. */',
      `export const illustrationProfiles = ${JSON.stringify(profiles)} as const;`,
      '',
      'export type IllustrationProfile = (typeof illustrationProfiles)[number];',
      '',
      '/**',
      " * Lazy loader per profile. Each loads that profile's metadata, SVG",
      ' * strings and image URLs on demand, so bundlers can split them per profile.',
      ' */',
      'export const illustrationLoaders: Record<',
      '  IllustrationProfile,',
      '  () => Promise<IllustrationLibrary>',
      '> = {',
      ...loaders,
      '};',
      '',
    ].join('\n'),
  );
};

const build = async () => {
  fs.rmSync(generatedDir, { recursive: true, force: true });
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.mkdirSync(distDir, { recursive: true });

  const profiles = listDirectories(sourceDir);
  console.log(`Building illustrations for ${profiles.length} profile(s)…`);

  const cssChunks: string[] = [];
  for (const profile of profiles) {
    cssChunks.push(await buildProfile(profile));
  }
  fs.writeFileSync(path.join(distDir, 'index.css'), cssChunks.join('\n'));

  writeIndex(profiles);
};

build().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
